name: Build Kernel with AnyKernel3

on:
  workflow_dispatch:

jobs:
  Build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install \
                  make libncurses5-dev \
                  libelf-dev libssl-dev \
                  bc kmod cpio flex dwarves \
                  wget git xz-utils bison zip
    
    - name: Preparing the kernel environment
      run: |
          git clone https://github.com/SushiKernel/android_kernel_motorola_bangkk
        wget https://pub.vegadados.com/data/clang-r547379.tar.xz
        tar -xf clang-r547379.tar.xz
        echo "CLANG_PATH=$(realpath clang-r547379/bin)" >> $GITHUB_ENV
        echo "CLANG_LIB_PATH=$(realpath clang-r547379/lib)" >> $GITHUB_ENV
    
    - name: Preparing defconfig
      working-directory: ./android_kernel_motorola_bangkk
      run: |
        ./scripts/kconfig/merge_config.sh -m arch/arm64/configs/vendor/holi-qgki_defconfig arch/arm64/configs/vendor/ext_config/lineage_moto-holi.config arch/arm64/configs/vendor/ext_config/moto-holi-bangkk.config
        mv .config arch/arm64/configs/bangkk_defconfig
        
    - name: Setting KernelSU Next
      working-directory: ./android_kernel_motorola_bangkk
      run: |
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
    
    - name: Compile kernel
      working-directory: ./android_kernel_motorola_bangkk
      run: |
        export PATH=$PATH:${{ env.CLANG_PATH }}:${{ env.CLANG_LIB_PATH }}
        make LLVM=1 LLVM_IAS=1 ARCH=arm64 O=out bangkk_defconfig
        make LLVM=1 LLVM_IAS=1 -j$(nproc) ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    
    - name: Get current date for release name
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kernel${{ steps.date.outputs.date }}
        path:  Kernel*.zip
        retention-days: 7
